
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SHREE
 */
public class withdrawhin extends javax.swing.JFrame {

    /**
     * Creates new form withdrawhin
     */
    public withdrawhin() {
        initComponents();
    }
 public class Data {
    public static String withdraw;
   

    public static String getwithamt() {
        return withdraw;
    }

    public static void setwithamt(String withdraw) {
        Data.withdraw= withdraw;
    }

    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("कॉसमॉस बैंक");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 83, 115, 30));

        jButton1.setText("<<पीछे");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 179, -1, -1));

        jButton2.setText("प्रवेश करना");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 179, -1, -1));

        jButton3.setText("रद्द करना");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 179, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\SHREE\\OneDrive\\Documents\\NetBeansProjects\\Bank Management\\src\\images\\image13.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Hindi h=new Hindi();
        h.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 String withdraw = jTextField1.getText();
    withdraweng.Data.setwithamt(withdraw);
       
        
        
        
        
        String cardNumber = login3.UserData.getCardNumber();
    String pin = login3.UserData.getPin();

    // Use the cardNumber and pin values as needed
    System.out.println("Card Number from login3: " + cardNumber);
    System.out.println("PIN from login3: " + pin);

    int amount = Integer.parseInt(jTextField1.getText());
    Connection con = null;
    ResultSet rs = null;
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        System.out.println("Driver registered successfully");
    } catch (Exception e) {
        System.out.println("Error in driver registration");
    }
    try {
        String url = "jdbc:mysql://localhost:3306/mysql";
        String username = "root";
        String password = "123@shree";

        // Create a connection to the database
        con = DriverManager.getConnection(url, username, password);
        Statement st = con.createStatement();

        if (amount <= 10000) {
            rs = st.executeQuery("select balance from banklogin where bankid=" + cardNumber + "");
            if (rs.next()) {
                int currentBalance = rs.getInt(1);
                if (amount <= (currentBalance - 1000)) {
                    int a = JOptionPane.showConfirmDialog(this, "क्या आप रसीद चाहते हैं?");
                    if (a == JOptionPane.YES_OPTION) {
                        // Deduct the withdrawal amount from the current balance
                        int newBalance = currentBalance - amount;

                        // Update the balance in the database
                        st.executeUpdate("update banklogin set balance=" + newBalance + " where bankid=" + cardNumber + "");

                        balance1hin b = new balance1hin();
                        this.setVisible(false);
                        b.setVisible(true);
                    } else {
                        Hindi e = new Hindi();
                        e.setVisible(true);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "दर्ज की गई राशि शेष राशि से अधिक है");
                    con.close();
                }
            }
        }
        if (amount > 10000) {
            JOptionPane.showMessageDialog(this, "सिर्फ 10000 ही निकाले जा सकेंगे");
        }
    } catch (Exception e) {
        System.out.println(e.getMessage());
    }      // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(withdrawhin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(withdrawhin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(withdrawhin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(withdrawhin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new withdrawhin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
